In [7]:
import numpy as np

def generate_instance(num_vertices, max_coord):
    # Gerar coordenadas aleatórias para os vértices
    vertices = np.random.randint(max_coord, size=(num_vertices, 2))
    
    # Criar matriz de adjacência inicialmente vazia
    adjacency_matrix = np.zeros((num_vertices, num_vertices))
    
    # Preencher a matriz de adjacência com arestas aleatórias
    for i in range(num_vertices):
        for j in range(i+1, num_vertices):
            # Determinar se há uma aresta entre os vértices i e j com uma probabilidade de 50%
            if np.random.random() < 0.5:
                adjacency_matrix[i, j] = 1
                adjacency_matrix[j, i] = 1
    
    return vertices, adjacency_matrix

# Exemplo de uso:
num_vertices = 6  # Número de vértices
max_coord = 10    # Máxima coordenada para os vértices

vertices, adjacency_matrix = generate_instance(num_vertices, max_coord)

print("Coordenadas dos vértices:")
print(vertices)
print("\nMatriz de adjacência:")
print(adjacency_matrix)


Coordenadas dos vértices:
[[2 7]
 [6 2]
 [4 6]
 [6 3]
 [5 0]
 [8 7]]

Matriz de adjacência:
[[0. 1. 0. 0. 1. 0.]
 [1. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 0.]
 [0. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]]


In [8]:
# deixar a heuristica de construcao inicial mais gulosa, para que a busca seja mais otimizada
# construir uma lista de arestas que possuem cruzamentos, e desfazer os cruzamentos que possuem mais cruzamentos
# trabalhar no GRASP com uma porcentagem dos 30% melhores, restringindo o tamanho da lista, testando posteriormente o alpha de aleatoriedade


def generate_instance(num_vertices, max_coord):
    # Gerar coordenadas aleatórias para os vértices
    vertices = np.random.randint(max_coord, size=(num_vertices, 2))
    
    # Criar matriz de adjacência inicialmente vazia
    adjacency_matrix = np.zeros((num_vertices, num_vertices))
    
    # Preencher a matriz de adjacência com arestas aleatórias
    for i in range(num_vertices):
        for j in range(i+1, num_vertices):
            # Determinar se há uma aresta entre os vértices i e j com uma probabilidade de 50%
            if np.random.random() < 0.5:
                adjacency_matrix[i, j] = 1
                adjacency_matrix[j, i] = 1
    
    return vertices, adjacency_matrix

def generate_random_solution(num_vertices):
    # Gerar uma solução aleatória
    return np.random.permutation(num_vertices)

def local_search(solution, adjacency_matrix):
    # Um procedimento de melhoria local simples: troca aleatória de dois vértices
    new_solution = solution.copy()
    idx1, idx2 = np.random.choice(len(solution), 2, replace=False)
    new_solution[idx1], new_solution[idx2] = new_solution[idx2], new_solution[idx1]
    return new_solution

def evaluate_solution(solution, adjacency_matrix):
    # Avaliar a solução calculando o custo total (nesse caso, o número de arestas na solução)
    total_edges = sum(adjacency_matrix[i, j] for i in solution for j in solution if i != j)
    return total_edges

def grasp(num_vertices, max_coord, num_iterations):
    best_solution = None
    best_solution_cost = float('inf')
    
    for _ in range(num_iterations):
        # Gerar uma solução inicial aleatória
        initial_solution = generate_random_solution(num_vertices)
        
        # Realizar a busca local na solução inicial
        improved_solution = local_search(initial_solution, adjacency_matrix)
        
        # Avaliar a solução melhorada
        solution_cost = evaluate_solution(improved_solution, adjacency_matrix)
        
        # Atualizar a melhor solução encontrada, se necessário
        if solution_cost < best_solution_cost:
            best_solution = improved_solution
            best_solution_cost = solution_cost
    
    return best_solution, best_solution_cost

# Exemplo de uso:
num_vertices = 6  # Número de vértices
max_coord = 10    # Máxima coordenada para os vértices
num_iterations = 10  # Número de iterações GRASP

vertices, adjacency_matrix = generate_instance(num_vertices, max_coord)
best_solution, best_solution_cost = grasp(num_vertices, max_coord, num_iterations)

print("Coordenadas dos vértices:")
print(vertices)
print("\nMatriz de adjacência:")
print(adjacency_matrix)
print("\nMelhor solução encontrada:")
print(best_solution)
print("Custo da melhor solução:", best_solution_cost)


Coordenadas dos vértices:
[[7 2]
 [9 5]
 [9 5]
 [3 0]
 [3 6]
 [9 8]]

Matriz de adjacência:
[[0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 1.]
 [0. 1. 1. 0. 1. 1.]
 [0. 0. 0. 1. 0. 1.]
 [1. 0. 1. 1. 1. 0.]]

Melhor solução encontrada:
[4 2 0 5 3 1]
Custo da melhor solução: 16.0
